[general]

makefile = 'makefiles/ubuntu.22.04.make'

# run at each value N times
runs = 6

# maximum time to wait on program
timeout = 3600

[commands]
# Available variables:
#   <BENCHMARK>:   the name of the benchmark being run
#   <LANGUAGE>: the language being tested
#   <BINARY>:   the executable binary being run
#   <INPUT>:    an input value (from 'values', below)

java = "java -cp . <BENCHMARK>"
rust = "<BINARY> <INPUT>"
ada = "<BINARY> <INPUT>"
cpp = "<BINARY> <INPUT>"
c = "<BINARY> <INPUT>"

[tools]
# build tools for benchmarks

java = 'javac'
rust = 'rustc'
ada = 'gnatmake'
cpp = 'g++-12'
c = 'gcc-12'


[options]
# flags for each tool

java = '-d . -cp .'
java_ext = ''

rust = '-L../data/dependencies/rust'
rust_ext = ''

ada = '-L../data/dependencies/ada'
ada_ext = ''

cpp = '-L../data/dependencies/cpp'
cpp_ext = ''

c = '-L../data/dependencies/c'
c_ext = ''

[filters]

# build only these directories (relative to root)
directories = [
    'programs/mandelbrot',
    'programs/nbody',
    'programs/fannkuchredux',
    'programs/spectralnorm'
]

# include additional files (relative to root)
include = []

# exclude these specific files (relative to root)
exclude = []

# ignore files with these extensions
ignore = []

[values]

mandelbrot = [
    1000, 
    2000
    # 3000,
    # 4000,
    # 5000
]

nbody = [
    10000, 
    20000
    # 30000,
    # 40000,
    # 50000
]

fannkuchredux = [
    9, 
    10
    # 11,
    # 12,
    # 13
]

spectralnorm = [
    1000, 
    2000
    # 3000,
    # 4000,
    # 5000
]

[data]
