[general]

makefile = 'makefiles/ubuntu.22.04.make'

# run at each value N times
runs = 6

# maximum time to wait on program
timeout = 3600

# memory sampling delay
sample = 0.2

[tools]
# build tools for benchmarks

rust = 'rustc'
c = 'gcc-12'
cpp = 'g++-12'
ada = 'gnatmake'

[options]
# flags for each tool

rust = '-C opt-level=3 -C target-cpu=ivybridge -C codegen-units=1 -L../data/dependencies/rust'
rust_ext = ''

c = '-march=ivybridge'
c_ext = '-lm -fopenmp'

cpp = '-mavx -march=ivybridge'
cpp_ext = '-fopenmp'

ada = '-march=ivybridge -gnatNp'
ada_ext = ''

[filters]

# build only these directories (relative to root)
directories = [
    'programs/mandelbrot',
    'programs/nbody',
    'programs/fannkuchredux',
    'programs/spectralnorm'
]

# include additional files (relative to root)
include = []

# exclude these specific files (relative to root)
exclude = []

# ignore files with these extensions
ignore = []

[values]

nbody = [
    10000, 
    20000
    # 30000,
    # 40000,
    # 50000
]

fannkuchredux = [
    9, 
    10
    # 11,
    # 12,
    # 13
]

spectralnorm = [
    1000, 
    2000
    # 3000,
    # 4000,
    # 5000
]

[data]

knucleotide = 'data/knucleotide-input.txt'
regexdna = 'data/regexdna-input.txt'
revcomp = 'data/revcomp-input.txt'
