[options]
initial = [ "-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=ivybridge", "-fopenmp", "-O0",]
extended = [ "-fopenmp",]

[dependencies]
path = "data/dependencies/cpp"
names = []
files = []
