[options]
initial = [ "-pipe", "-Wall", "-O3", "-fomit-frame-pointer", "-march=ivybridge", "-fopenmp", "spectralnorm.gcc-4.c", "-o", "spectralnorm.gcc-4.gcc_run", "-lm", "rm",]
extended = []

[dependencies]
path = "PosixPath('data/dependencies/c')"
names = []
