[options]
initial = [ "-C", "opt-level=3", "-C", "target-cpu=ivybridge", "-C", "codegen-units=1", "-L", "/opt/src/rust-libs",]
extended = []

[dependencies]
path = "PosixPath('data/dependencies/rust')"
names = [ "rust:rayon",]
