[options]
initial = [ "-C", "opt-level=3", "-C", "target-cpu=ivybridge", "-C", "codegen-units=1",]
extended = []

[dependencies]
path = "data/dependencies/rust"
names = [ "rust:rayon:1.7.0",]
files = []
