[options]
initial = [ "-pipe", "-Wall", "-O3", "-fomit-frame-pointer", "-march=ivybridge", "-fopenmp", "mandelbrot.gcc-4.c", "-o", "mandelbrot.gcc-4.gcc_run",]
extended = []

[dependencies]
path = "PosixPath('data/dependencies/c')"
names = []
